export { default as KitService } from './Kit'
export { default as CategoriaService } from './Categoria'
export { default as LicenseService } from './License'
export { default as AssetService } from './Asset'
export { default as PersonService } from './Person'
export { default as SedeService } from './Sede'
