const ROUTES = {
  MOBILE_MODULE: '/mobile-module',
  LICENSE_MODULE: '/license-module',
  ASSET_MODULE: '/asset-module',
  KIT_ASSIGNMENT: 'assignment',
  KIT_MAINTENANCE: 'maintenance',
  LINE_ASSIGNMENT: 'line-assignment',
  LICENSE_ASSIGNMENT: 'assignment',
  LICENSE_MAINTENANCE: 'maintenance',
  LICENSES: '/licenses',
  ASSETS_ASSIGNMENT: 'assignment',
  ASSETS_MAINTENANCE: 'maintenance',
  ASSETS: '/assets',
  LOGIN: '/login',
  KIT_REPORT: 'report',
  ASSETS_REPORT: 'report',
  LICENSE_REPORT: 'report',
  DASHBOARD_LICENSE: 'dashboard'
}

export const SUB_ROUTES = {
  MOBILE_MODULE: {
    KIT_ASSIGNMENT: `${ROUTES.MOBILE_MODULE}/${ROUTES.KIT_ASSIGNMENT}`,
    KIT_MAINTENANCE: `${ROUTES.MOBILE_MODULE}/${ROUTES.KIT_MAINTENANCE}`,
    KIT_REPORT: `${ROUTES.MOBILE_MODULE}/${ROUTES.KIT_REPORT}`
  },
  LICENSE_MODULE: {
    LICENSE_ASSIGNMENT: `${ROUTES.LICENSE_MODULE}/${ROUTES.LICENSE_ASSIGNMENT}`,
    LICENSE_MAINTENANCE: `${ROUTES.LICENSE_MODULE}/${ROUTES.LICENSE_MAINTENANCE}`,
    LICENSE_REPORT: `${ROUTES.LICENSE_MODULE}/${ROUTES.LICENSE_REPORT}`
  },
  ASSET_MODULE: {
    ASSETS_ASSIGNMENT: `${ROUTES.ASSET_MODULE}/${ROUTES.ASSETS_ASSIGNMENT}`,
    ASSETS_MAINTENANCE: `${ROUTES.ASSET_MODULE}/${ROUTES.ASSETS_MAINTENANCE}`,
    ASSETS_REPORT: `${ROUTES.ASSET_MODULE}/${ROUTES.ASSETS_REPORT}`
  }
}

export default ROUTES
